name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # runs daily at midnight UTC
  workflow_dispatch:               # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bhaveshgadling77
          template: terminal
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          config_theme: github_dark
          plugin_isocalendar_duration: full-year
